// store-itemstore.ts
import { defineStore } from 'pinia';
import type { Item } from '~/types/item-type';

export const useItemStore = defineStore('itemStore', {
  state: () => ({
    items: [
      {
        userId: "user1",
        id: "item1",
        name: "iPhone",
        model: "iPhone 16",
        type: "Phone",
        brand: "iPhone",
        weight: 2.3,
        images: ["https://via.placeholder.com/176x155", "https://via.placeholder.com/176x155"],
        video: null,
        sellerIdPhoto: "https://via.placeholder.com/100",
        height: 1.5,
        status: "Almost new",
        description: "All new iPhone 16",
    },
    {
        userId: "user2",
        id: "item2",
        name: "Huawei",
        model: "Huawei Nova 7i",
        type: "Phone",
        brand: "Huawei",
        weight: 2.5,
        images: ["https://via.placeholder.com/176x155", "https://via.placeholder.com/176x155"],
        video: null,
        sellerIdPhoto: "https://via.placeholder.com/100",
        height: 1.4,
        status: "Almost new",
        description: "Huawei Nova 7i",
    },
    {
        userId: "user3",
        id: "item3",
        name: "Samsung",
        model: "Samsung Galaxy S24",
        type: "Phone",
        brand: "Samsung",
        weight: 0.1,
        images: ["https://via.placeholder.com/176x155", "https://via.placeholder.com/176x155"],
        video: null,
        sellerIdPhoto: "https://via.placeholder.com/100",
        height: 0.1,
        status: "Slightly Worn",
        description: "The best Samsung phone",
    },
    {
        userId: "user4",
        id: "item4",
        name: "Cherry Mobile",
        model: "Aqua SV",
        type: "Phone",
        brand: "Cherry Mobile",
        weight: 15.0,
        images: ["https://via.placeholder.com/176x155", "https://via.placeholder.com/176x155"],
        video: null,
        sellerIdPhoto: "https://via.placeholder.com/100",
        height: 2.5,
        status: "Slightly used",
        description: "New Cherry Mobile smartphone",
    },
    {
        userId: "user5",
        id: "item5",
        name: "iPhone",
        model: "iPhone 13",
        type: "Phone",
        brand: "Apple",
        weight: 0.2,
        images: ["https://via.placeholder.com/176x155", "https://via.placeholder.com/176x155"],
        video: null,
        sellerIdPhoto: "https://via.placeholder.com/100",
        height: 0.2,
        status: "Defective",
        description: "Smartphone with minor defects.",
    },
    {
      userId: "user6",
      id: "item5",
      name: "iPhone",
      model: "iPhone 13",
      type: "Phone",
      brand: "Apple",
      weight: 0.2,
      images: ["https://via.placeholder.com/176x155", "https://via.placeholder.com/176x155"],
      video: null,
      sellerIdPhoto: "https://via.placeholder.com/100",
      height: 0.2,
      status: "Defective",
      description: "Smartphone with minor defects.",
  },
  {
    userId: "user7",
    id: "item5",
    name: "iPhone",
    model: "iPhone 13",
    type: "Phone",
    brand: "Apple",
    weight: 0.2,
    images: ["https://via.placeholder.com/176x155", "https://via.placeholder.com/176x155"],
    video: null,
    sellerIdPhoto: "https://via.placeholder.com/100",
    height: 0.2,
    status: "Defective",
    description: "Smartphone with minor defects.",
},
{
  userId: "user8",
  id: "item5",
  name: "iPhone",
  model: "iPhone 13",
  type: "Phone",
  brand: "Apple",
  weight: 0.2,
  images: ["https://via.placeholder.com/176x155", "https://via.placeholder.com/176x155"],
  video: null,
  sellerIdPhoto: "https://via.placeholder.com/100",
  height: 0.2,
  status: "Defective",
  description: "Smartphone with minor defects.",
},
    ] as Item[]
  }),
  getters: {
    getItems: (state) => state.items
  }
});
